### ISSUE TITLE
Movie anywhere has added arbitration terms. 

### ISSUE THREAD

**Issue by huskyhi** [lynnpepin/arbitration-opt-out-templates#4]
I just received noticed that Movies Anywhere is adding an arbitration clause to their terms of use. Notification email says you can opt out but they provide no instructions to do so.

**Comment by lynnpepin** [comment]
Thank you for the heads up! Could you provide a copy of the email? I can't find any opt-out provision in their Terms of Service, but having the language in the email might help.

**Comment by huskyhi** [comment]
** We’re Updating our Terms of Use**

<head></head>
As a user of the Movies Anywhere service, we want to let you know that we are updating the Movies Anywhere Terms of Use. We are making certain clarifications to existing terms and updating the arbitration agreement to be more specific about the procedures for resolving any disputes relating to your Movies Anywhere account and our services and to offer you the choice to “opt out” of resolving disputes through arbitration. We encourage you to review the terms in full. The updates will be effective as of June 12, 2024, and at that time will govern your use and enjoyment of the Movies Anywhere service. We continue our commitment to giving you the best experience possible to enjoy and grow your movie collection.By continuing to use or access the Movies Anywhere website or applications or otherwise engage with Movies Anywhere on or after the effective date above, you accept and agree to the updated Terms of Use. Thank you for making Movies Anywhere part of your entertainment experience.The Movies Anywhere Team | As a user of the Movies Anywhere service, we want to let you know that we are updating the Movies Anywhere Terms of Use. We are making certain clarifications to existing terms and updating the arbitration agreement to be more specific about the procedures for resolving any disputes relating to your Movies Anywhere account and our services and to offer you the choice to “opt out” of resolving disputes through arbitration. We encourage you to review the terms in full. The updates will be effective as of June 12, 2024, and at that time will govern your use and enjoyment of the Movies Anywhere service. We continue our commitment to giving you the best experience possible to enjoy and grow your movie collection.By continuing to use or access the Movies Anywhere website or applications or otherwise engage with Movies Anywhere on or after the effective date above, you accept and agree to the updated Terms of Use. Thank you for making Movies Anywhere part of your entertainment experience.The Movies Anywhere Team |  
-- | -- | --
As a user of the Movies Anywhere service, we want to let you know that we are updating the Movies Anywhere Terms of Use. We are making certain clarifications to existing terms and updating the arbitration agreement to be more specific about the procedures for resolving any disputes relating to your Movies Anywhere account and our services and to offer you the choice to “opt out” of resolving disputes through arbitration. We encourage you to review the terms in full. The updates will be effective as of June 12, 2024, and at that time will govern your use and enjoyment of the Movies Anywhere service. We continue our commitment to giving you the best experience possible to enjoy and grow your movie collection.By continuing to use or access the Movies Anywhere website or applications or otherwise engage with Movies Anywhere on or after the effective date above, you accept and agree to the updated Terms of Use. Thank you for making Movies Anywhere part of your entertainment experience.The Movies Anywhere Team
 

As a user of the Movies Anywhere service, we want to let you know that we are updating the Movies Anywhere Terms of Use. We are making certain clarifications to existing terms and updating the arbitration agreement to be more specific about the procedures for resolving any disputes relating to your Movies Anywhere account and our services and to offer you the choice to “opt out” of resolving disputes through arbitration. We encourage you to review the terms in full. The updates will be effective as of June 12, 2024, and at that time will govern your use and enjoyment of the Movies Anywhere service. We continue our commitment to giving you the best experience possible to enjoy and grow your movie collection.

By continuing to use or access the Movies Anywhere website or applications or otherwise engage with Movies Anywhere on or after the effective date above, you accept and agree to the updated Terms of Use. Thank you for making Movies Anywhere part of your entertainment experience.

The Movies Anywhere Team
 



Registration with Movies Anywhere required. Open to U.S. residents 13+. Visit [MoviesAnywhere.com](https://links.email.moviesanywhere.com/ls/click?upn=u001.YOmhGVxK5EVVFO7JDPOc5O2LmszH-2FAt6G6Rd3c7c7rBXbiGUbfwp9n4gpnsH85v9gdXH_gczncEOTbW-2B1VXPIf-2FbkB7PaJBP1P8AfrVG-2BONvnyN8NbnUn4-2FaRYYz1lGMQfLOS8uU0TjTgyfP0QldS999XTd2dGSc1TmswHA6b6Fvcccc8Thx68v5FJ-2B-2FD0x7gCm7tFfampYKbatNWXb4767R31it2VCit37-2FoYdyI9FL2VeKNt8-2BTh42lpPgmvczHzADb1vnveTIdghUCV7E0uO8zCPaYQEisSlRCtQo1WUQSofmWYZ15OPni3qFFi1-2FJMSBc5T1g0mSTIkN9MX1l-2BGdUdf4FCwYzgMz2rQSYGCjigXYvf2kjNBso0Vy0VAV2uhYGDCSPS3-2Fyhgyg-2FC9H6kfYU0S2OZxbEm-2Br00-2BWVKj9A0fyMCrSPoNyhZC-2FT89-2BnTrHEwBs4ArIANqKna5AFT01apwX3C5-2FyicMLBVivuk6ZnxA1acwYAEdyYe8UM1SHUHS9KZXKH0nr2-2ByjM6rZCWGmZoeYm844EYRNM1SqoboypjE1SHrExynkOWBhT3b5jCM0qKVAKAD-2Bnap2OhBHh69YAOEItCk0Uph-2BZ0-2BVJAnwhuKeews2xUuGI45RW691ldXuwvWHkpk-2BOdbCepH7ksiy4XJZtWFiX-2BGZ725Nqs6OYvQIOQXU8tnJBRFHyMyAPiptObZuKgQvfRgLeEWw-2Frmew-3D-3D) for complete details & terms and conditions.

[Terms of Use](https://links.email.moviesanywhere.com/ls/click?upn=u001.YOmhGVxK5EVVFO7JDPOc5O2LmszH-2FAt6G6Rd3c7c7rBXbiGUbfwp9n4gpnsH85v9DCfF_gczncEOTbW-2B1VXPIf-2FbkB7PaJBP1P8AfrVG-2BONvnyN8NbnUn4-2FaRYYz1lGMQfLOS8uU0TjTgyfP0QldS999XTd2dGSc1TmswHA6b6Fvcccc8Thx68v5FJ-2B-2FD0x7gCm7tFfampYKbatNWXb4767R31it2VCit37-2FoYdyI9FL2VeKNt8-2BTh42lpPgmvczHzADb1vnveTIdghUCV7E0uO8zCPaYQEisSlRCtQo1WUQSofmWYZ15OPni3qFFi1-2FJMSBc5T1g0mSTIkN9MX1l-2BGdUdf4FCwYzgMz2rQSYGCjigXYvf2kjNBso0Vy0VAV2uhYGDCSPS3-2Fyhgyg-2FC9H6kfYU0S2OZxbEm-2Br00-2BWVKj9A0fyMCrSPoNyhZC-2FT89-2BnTrHEwBs4ArIANqKna5AFT01apwX3C5-2FyicMLBVivuk6ZnxA1acwYAEdyYe8UM1SHUHS9KZXKH0nr2-2ByjM6rZCWGmZoeYm844EYRNM1SqoboypjE1SHrExynkOWBhT3b5jCMMArMSCUAqphcNS0pDn2fLnLfrgiO-2FB5Cj72g-2BUf1s5mOcWoNBe-2FLDavJ6SpBaVoYz4zBRUghykdFUALIBB7tkOK-2BSzxmyNSqYDRoh6ic5lGvsgrrdIvpqFqEpuk06-2FmohUnTY2AvYQxfRTNnrSeCGA-3D-3D) | [Privacy Policy](https://links.email.moviesanywhere.com/ls/click?upn=u001.YOmhGVxK5EVVFO7JDPOc5O2LmszH-2FAt6G6Rd3c7c7rBIxa-2BWRyaqkhngiNSiMAw-2BdqdUBl3CQgARA-2Fp4LZV04g-3D-3DAUxW_gczncEOTbW-2B1VXPIf-2FbkB7PaJBP1P8AfrVG-2BONvnyN8NbnUn4-2FaRYYz1lGMQfLOS8uU0TjTgyfP0QldS999XTd2dGSc1TmswHA6b6Fvcccc8Thx68v5FJ-2B-2FD0x7gCm7tFfampYKbatNWXb4767R31it2VCit37-2FoYdyI9FL2VeKNt8-2BTh42lpPgmvczHzADb1vnveTIdghUCV7E0uO8zCPaYQEisSlRCtQo1WUQSofmWYZ15OPni3qFFi1-2FJMSBc5T1g0mSTIkN9MX1l-2BGdUdf4FCwYzgMz2rQSYGCjigXYvf2kjNBso0Vy0VAV2uhYGDCSPS3-2Fyhgyg-2FC9H6kfYU0S2OZxbEm-2Br00-2BWVKj9A0fyMCrSPoNyhZC-2FT89-2BnTrHEwBs4ArIANqKna5AFT01apwX3C5-2FyicMLBVivuk6ZnxA1acwYAEdyYe8UM1SHUHS9KZXKH0nr2-2ByjM6rZCWGmZoeYm844EYRNM1SqoboypjE1SHrExynkOWBhT3b5jCMSxzvE-2FBqzjbGCYpZxIn7JnNYi4hgjp7FVK7wBffoDcV3HJPeH0YMEscTnPvM3OtYCQkCO5kU6LXuZNg0-2Ffg-2F4-2FaOLwJ494okxMuD-2FGBujXwQpwbtHTH1cgF9SSAhDhbY-2BtbYiac1ycuUVM3QrHZYlQ-3D-3D)

Movies Anywhere, LLC, Attn: Customer Relations, Mail Code MA7620
500 South Buena Vista St., Burbank, CA 91521

All rights reserved

Movies Anywhere is a trademark of Movies Anywhere, LLC.

©2024 Movies Anywhere

**Comment by lynnpepin** [comment]
Thanks for sharing this. Yep, no hints here at all on how to opt out.

It seems they've had arbitration for awhile, but are now _adding_ the opportunity to opt-out. Total speculation, but I wonder if their clause was found unenforceable in a case for having no opt-out option?

I'll take another look after June 12th to see if they add the opt-out option.

**Comment by huskyhi** [comment]
Just got a reply from their support says June 12th 2024 update will include opt out instructions

**Comment by lynnpepin** [comment]
https://moviesanywhere.com/terms-of-use Still waiting on them to update the ToS...  It reads March 12th, but people are getting emails now saying it will be July 22nd instead. Will check back periodically
